import img from "../Product_images/tea.jpg";
import img1 from "../Product_images/Chips1.webp";
import img2 from "../Product_images/Chips2.webp";
import img3 from "../Product_images/Chips3.webp";
import img4 from "../Product_images/Chips4.webp";
import img5 from "../Product_images/Chips5.webp";
import img6 from "../Product_images/Chips6.webp";
import img7 from "../Product_images/Chips7.webp";
import img8 from "../Product_images/Chips8.webp";
import img9 from "../Product_images/Chips9.webp";
import img10 from "../Product_images/Chips10.webp";
import img11 from "../Product_images/Chips11.webp";
import img12 from "../Product_images/Chips12.webp";
import img13 from "../Product_images/Chips13.webp";
import img14 from "../Product_images/Chips14.webp";
import img15 from "../Product_images/Chips15.webp";
import img16 from "../Product_images/Chips16.webp";
import img17 from "../Product_images/Chips17.webp";
import img18 from "../Product_images/Chips18.webp";
import img19 from "../Product_images/Chips19.webp";
import img20 from "../Product_images/Chips20.webp";
import img21 from "../Product_images/vegi1.webp";
import img22 from "../Product_images/vegi2.webp";
import img23 from "../Product_images/vegi3.webp";
import img24 from "../Product_images/vegi4.webp";
import img25 from "../Product_images/vegi5.webp";
import img26 from "../Product_images/vegi6.webp";
import img27 from "../Product_images/vegi7.webp";
import img28 from "../Product_images/vegi8.webp";
import img29 from "../Product_images/vegi9.webp";
import img30 from "../Product_images/vegi10.webp";
import img31 from "../Product_images/vegi11.webp";
import img32 from "../Product_images/vegi12.webp";
import img33 from "../Product_images/vegi13.webp";
import img34 from "../Product_images/vegi14.webp";
import img35 from "../Product_images/vegi15.webp";
import img36 from "../Product_images/vegi16.webp";
import img37 from "../Product_images/vegi17.webp";
import img38 from "../Product_images/vegi18.webp";
import img39 from "../Product_images/vegi19.webp";
import img40 from "../Product_images/vegi20.webp";
import img41 from "../Product_images/vegi21.webp";
import img42 from "../Product_images/vegi22.webp";
import img43 from "../Product_images/vegi23.webp";
import img44 from "../Product_images/vegi24.webp";
import img45 from "../Product_images/vegi25.webp";
import img46 from "../Product_images/vegi26.webp";
import img47 from "../Product_images/vegi27.webp";
import img48 from "../Product_images/vegi28.webp";
import img49 from "../Product_images/vegi29.webp";
import img50 from "../Product_images/vegi30.webp";
import img51 from "../Product_images/vegi31.webp";
import img52 from "../Product_images/vegi32.webp";
import img53 from "../Product_images/vegi33.webp";
import img54 from "../Product_images/vegi34.webp";
import img55 from "../Product_images/vegi35.webp";
import img56 from "../Product_images/vegi36.webp";
import img57 from "../Product_images/vegi37.webp";
import img58 from "../Product_images/vegi38.webp";
import img59 from "../Product_images/vegi39.webp";
import img60 from "../Product_images/vegi18.webp";


import img61 from "../Product_images/Fruit01.webp";
import img62 from "../Product_images/Fruit02.webp";
import img63 from "../Product_images/Fruit03.webp";
import img64 from "../Product_images/Fruit04.webp";
import img65 from "../Product_images/Fruit05.webp";
import img66 from "../Product_images/Fruit06.webp";
import img67 from "../Product_images/Fruit07.webp";
import img68 from "../Product_images/Fruit08.webp";
import img69 from "../Product_images/Fruit09.webp";
import img70 from "../Product_images/Fruit10.webp";
import img71 from "../Product_images/Fruit11.webp";
import img72 from "../Product_images/Fruit12.webp";
import img73 from "../Product_images/Fruit13.webp";
import img74 from "../Product_images/Fruit14.webp";
import img75 from "../Product_images/Fruit15.webp";
import img76 from "../Product_images/Fruit16.webp";
import img77 from "../Product_images/Fruit17.webp";
import img78 from "../Product_images/Fruit18.webp";
import img79 from "../Product_images/Fruit19.webp";
import img80 from "../Product_images/Fruit20.webp";
import img81 from "../Product_images/Fruit21.webp";
import img82 from "../Product_images/Fruit22.webp";
import img83 from "../Product_images/Fruit23.webp";
import img84 from "../Product_images/Fruit24.webp";
import img85 from "../Product_images/Fruit25.webp";
import img86 from "../Product_images/Fruit26.webp";
import img87 from "../Product_images/Fruit27.webp";
import img88 from "../Product_images/Fruit28.webp";
import img89 from "../Product_images/Fruit29.webp";
import img90 from "../Product_images/Fruit30.webp";
import img91 from "../Product_images/Fruit31.webp";
import img92 from "../Product_images/Fruit32.webp";
import img93 from "../Product_images/Fruit33.webp";
import img94 from "../Product_images/Fruit34.webp";
import img95 from "../Product_images/Fruit35.webp";
import img96 from "../Product_images/Fruit36.webp";
import img97 from "../Product_images/Fruit37.webp";
import img98 from "../Product_images/Fruit38.webp";
import img99 from "../Product_images/Fruit39.webp";
import img100 from "../Product_images/Fruit40.webp";


import img101 from "../Product_images/Dairy1.webp";
import img102 from "../Product_images/Dairy02.webp";
import img103 from "../Product_images/Dairy03.webp";
import img104 from "../Product_images/Dairy04.webp";
import img105 from "../Product_images/Dairy05.webp";
import img106 from "../Product_images/Dairy06.webp";
import img107 from "../Product_images/Dairy07.webp";
import img108 from "../Product_images/Dairy08.webp";
import img109 from "../Product_images/Dairy09.webp";
import img110 from "../Product_images/Dairy10.webp";
import img111 from "../Product_images/Dairy11.webp";
import img112 from "../Product_images/Dairy12.webp";
import img113 from "../Product_images/Dairy13.webp";
import img114 from "../Product_images/Dairy14.webp";
import img115 from "../Product_images/Dairy15.webp";
import img116 from "../Product_images/Dairy16.webp";
import img117 from "../Product_images/Dairy17.webp";
import img118 from "../Product_images/Dairy18.webp";
import img119 from "../Product_images/Dairy19.webp";
import img120 from "../Product_images/Dairy20.webp";
import img121 from "../Product_images/Dairy21.webp";
import img122 from "../Product_images/Dairy22.webp";
import img123 from "../Product_images/Dairy23.webp";
import img124 from "../Product_images/Dairy24.webp";
import img125 from "../Product_images/Dairy25.webp";
import img126 from "../Product_images/Dairy26.webp";
import img127 from "../Product_images/Dairy27.webp";
import img128 from "../Product_images/Dairy28.webp";
import img129 from "../Product_images/Dairy29.webp";
import img130 from "../Product_images/Dairy30.webp";
import img131 from "../Product_images/Dairy31.webp";
import img132 from "../Product_images/Dairy32.webp";
import img133 from "../Product_images/Dairy33.webp";
import img134 from "../Product_images/Dairy34.webp";
import img135 from "../Product_images/Dairy35.webp";
import img136 from "../Product_images/Dairy36.webp";
import img137 from "../Product_images/Dairy37.webp";
import img138 from "../Product_images/Dairy38.webp";
import img139 from "../Product_images/Dairy39.webp";
import img140 from "../Product_images/Dairy40.webp";
import img141 from "../Product_images/Dairy41.webp";
import img142 from "../Product_images/Dairy42.webp";
import img143 from "../Product_images/Dairy43.webp";
import img144 from "../Product_images/Dairy44.webp";
import img145 from "../Product_images/Dairy45.webp";
import img146 from "../Product_images/Dairy46.webp";
import img147 from "../Product_images/Dairy47.webp";
import img148 from "../Product_images/Dairy48.webp";
import img149 from "../Product_images/Dairy49.webp";
import img150 from "../Product_images/Dairy50.webp";
import img151 from "../Product_images/Dairy51.webp";
import img152 from "../Product_images/Dairy52.webp";




import img153 from "../Product_images/Home1.webp";
import img154 from "../Product_images/Home2.webp";
import img155 from "../Product_images/Home3.webp";
import img156 from "../Product_images/Home4.webp";
import img157 from "../Product_images/Home5.webp";
import img158 from "../Product_images/Home6.webp";
import img159 from "../Product_images/Home7.webp";
import img160 from "../Product_images/Home8.webp";
import img161 from "../Product_images/Home9.webp";
import img162 from "../Product_images/Home10.webp";
import img163 from "../Product_images/Home11.webp";
import img164 from "../Product_images/Home12.webp";
import img165 from "../Product_images/Home13.webp";
import img166 from "../Product_images/Home14.webp";
import img167 from "../Product_images/Home15.webp";
import img168 from "../Product_images/Home16.webp";
import img169 from "../Product_images/Home17.webp";
import img170 from "../Product_images/Home18.webp";
import img171 from "../Product_images/Home19.webp";
import img172 from "../Product_images/Home20.webp";
import img173 from "../Product_images/Home21.webp";
import img174 from "../Product_images/Home22.webp";
import img175 from "../Product_images/Home23.webp";
import img176 from "../Product_images/Home24.webp";
import img177 from "../Product_images/Home25.webp";
import img178 from "../Product_images/Home26.webp";
import img179 from "../Product_images/Home27.webp";
import img180 from "../Product_images/Home28.webp";
import img181 from "../Product_images/Home29.webp";
import img182 from "../Product_images/Home30.webp";
import img183 from "../Product_images/Home31.webp";
import img184 from "../Product_images/Home32.webp";
import img185 from "../Product_images/Home33.webp";
import img187 from "../Product_images/Home34.webp";
import img186 from "../Product_images/Home35.webp";
import img188 from "../Product_images/Home36.webp";
import img189 from "../Product_images/Home37.webp";
import img190 from "../Product_images/Home38.webp";
import img191 from "../Product_images/Home39.webp";
import img192 from "../Product_images/Home40.webp";


import img193 from "../Product_images/Bakery1.webp";
import img194 from "../Product_images/Bakery2.webp";
import img195 from "../Product_images/Bakery3.webp";
import img196 from "../Product_images/Bakery4.webp";
import img197 from "../Product_images/Bakery5.webp";
import img198 from "../Product_images/Bakery6.webp";
import img199 from "../Product_images/Bakery7.webp";
import img200 from "../Product_images/Bakery8.webp";
import img201 from "../Product_images/Bakery9.webp";
import img202 from "../Product_images/Bakery10.webp";
import img203 from "../Product_images/Bakery11.webp";
import img204 from "../Product_images/Bakery12.webp";
import img205 from "../Product_images/Bakery13.webp";
import img206 from "../Product_images/Bakery14.webp";
import img207 from "../Product_images/Bakery15.webp";
import img208 from "../Product_images/Bakery16.webp";
import img209 from "../Product_images/Bakery17.webp";
import img210 from "../Product_images/Bakery18.webp";
import img211 from "../Product_images/Bakery19.webp";
import img212 from "../Product_images/Bakery20.webp";
import img213 from "../Product_images/Bakery21.webp";
import img214 from "../Product_images/Bakery22.webp";
import img215 from "../Product_images/Bakery23.webp";
import img216 from "../Product_images/Bakery24.webp";
import img217 from "../Product_images/Bakery25.webp";
import img218 from "../Product_images/Bakery26.webp";
import img219 from "../Product_images/Bakery27.webp";
import img220 from "../Product_images/Bakery28.webp";
import img221 from "../Product_images/Bakery29.webp";
import img222 from "../Product_images/Bakery30.webp";
import img223 from "../Product_images/Bakery31.webp";
import img224 from "../Product_images/Bakery32.webp";
import img225 from "../Product_images/Bakery33.webp";
import img226 from "../Product_images/Bakery34.webp";
import img227 from "../Product_images/Bakery35.webp";
import img228 from "../Product_images/Bakery36.webp";
import img229 from "../Product_images/Bakery37.webp";
import img230 from "../Product_images/Bakery38.webp";
import img231 from "../Product_images/Bakery39.webp";
import img232 from "../Product_images/Bakery40.webp";


import img233 from "../Product_images/Baby1.webp";
// import img234 from "../Product_images/Baby2.webp";
// import img235 from "../Product_images/Baby3.webp";
// import img236 from "../Product_images/Baby4.webp";
// import img237 from "../Product_images/Baby5.webp";
// import img238 from "../Product_images/Baby6.webp";
// import img239 from "../Product_images/Baby7.webp";
// import catlog1 from "../Product_images/catlog1"
// export const categories = [
//   { name: "Fruits & Vegetables", image: {catlog1} }
//   // { name: "Atta, Rice, Oil & Dals", image: "atta_rice_oil_dals.png" },
//   // { name: "Masala & Dry Fruits", image: "masala_dry_fruits.png" },
//   // { name: "Sweet Cravings", image: "sweet_cravings.png" },
//   // { name: "Toys & Sports", image: "toys_sports.png" },
//   // { name: "Apparel & Lifestyle", image: "apparel_lifestyle.png" },
//   // { name: "Jewellery & Accessories", image: "jewellery_accessories.png" },
//   // { name: "Frozen Food", image: "frozen_food.png" },
//   // { name: "Ice Creams & More", image: "ice_creams_more.png" },
//   // { name: "Packaged Food", image: "packaged_food.png" },
//   // { name: "Dairy, Bread & Eggs", image: "dairy_bread_eggs.png" },
//   // { name: "Cold Drinks & Juices", image: "cold_drinks_juices.png" },
//   // { name: "Munchies & Chips", image: "munchies_chips.png" },
// ];


export const Api = [{
  mainid: "A1",
  id: 1,
  product: img1,
  product_name: "Too Yumm! Sour Cream & Onion Veggie Stix ,Munching Snack,Movie, Game, Parties Chips  (65 g)",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 2,
  product: img2,
  product_name: "Pringles Potato Chips Sour Cream & Onion Flavor Pack of 4, Crispy Snack for Game Nights Chips  (4 x 107 g)",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 3,
  product: img3,
  product_name: "Pringles Potato Chips Desi Masala Tadka Flavor Pack of 4, Crispy Snack for Game Nights Chips  (4 x 102 g)",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 4,
  product: img4,
  product_name: "Pringles Potato Chips Peri Peri Flavor Pack of 4, Crispy Snack for Movie & Game Nights Chips  (4 x 102 g)",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 5,
  product: img5,
  product_name: "Pringles Potato Chips Pizza Flavor Pack of 4, Crispy Snack for Movie & Game Nights Chips  (4 x 102 g)",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 6,
  product: img6,
  product_name: "Beyond Snack Kerala Banana - Peri Peri Chips  (3 x 100 g)",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 7,
  product: img7,
  product_name: "Bingo Potato Chips Hot & Spicy Korean Style Chips  (90 g)",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 8,
  product: img8,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 9,
  product: img9,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 10,
  product: img10,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 11,
  product: img11,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 12,
  product: img12,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 13,
  product: img13,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 14,
  product: img14,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 15,
  product: img15,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 16,
  product: img16,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 17,
  product: img17,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 18,
  product: img18,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
}, {
  mainid: "A1",
  id: 19,
  product: img19,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
},
{
  mainid: "A1",
  id: 20,
  product: img20,
  product_name: "CHIPS",
  rateing: "4.1",
  quantity: 128,
  current_price: 32,
  mrp: 35,
  discount: 8
},

];
export const Api2 = [
  {
    mainid: "A2",
    id: 1,
    product: img21,
    product_name: "Garlic 250g",
    rateing: "4.1",
    quantity: "250g",
    current_price: 95,
    mrp: 120,
    discount: 4,
  },
  {
    mainid: "A2",
    id: 2,
    product: img22,
    product_name: "Coconut 250g",
    rateing: "4.1",
    quantity: "250g",
    current_price: 120,
    mrp: 150,
    discount: 5,
  },
  {
    mainid: "A2",
    id: 3,
    product: img23,
    product_name: "Cauliflower 1 unit",
    rateing: "4",
    quantity: "1",
    current_price: 105,
    mrp: 121,
    discount: 13,
  },
  {
    mainid: "A2",
    id: 4,
    product: img24,
    product_name: "Capsicum 500g",
    rateing: "4.3",
    quantity: "500g",
    current_price: 43,
    mrp: 70,
    discount: 38,
  },
  {
    mainid: "A2",
    id: 5,
    product: img25,
    product_name: "Chill Green 200g",
    rateing: "4.2",
    quantity: "200g",
    current_price: 22,
    mrp: 50,
    discount: 56,
  },
  {
    mainid: "A2",
    id: 6,
    product: img26,
    product_name: "Ginger 100g",
    rateing: "4.1",
    quantity: "100g",
    current_price: 13,
    mrp: 78,
    discount: 83,
  },
  {
    mainid: "A2",
    id: 7,
    product: img27,
    product_name: "Ginger 250g",
    rateing: "4.3",
    quantity: "250g",
    current_price: 26,
    mrp: 65,
  },
  {
    mainid: "A2",
    id: 8,
    product: img28,
    product_name: "Garlic 100g",
    rateing: "4.1",
    quantity: "100g",
    current_price: 19,
    mrp: 50,
    discount: 62,
  },
  {
    mainid: "A2",
    id: 9,
    product: img29,
    product_name: "Potato Agra 1 kg",
    rateing: "4.3",
    quantity: "1kg",
    current_price: 40,
    mrp: 56,
    discount: 4,
  },
  {
    mainid: "A2",
    id: 10,
    product: img30,
    product_name: "Bitter gourd 500g",
    rateing: "4",
    quantity: "500g",
    current_price: 27,
    mrp: 50,
    discount: 46,
  },
  {
    mainid: "A2",
    id: 11,
    product: img31,
    product_name: "Cucumber Local 500g",
    rateing: "3.8",
    quantity: "500g",
    current_price: 34,
    mrp: 50,
    discount: 32,
  },
  {
    mainid: "A2",
    id: 12,
    product: img32,
    product_name: "Sweet Corn 2 unit",
    rateing: "4",
    quantity: "2 unit",
    current_price: 37,
    mrp: 70,
    discount: 47,
  },
  {
    mainid: "A2",
    id: 13,
    product: img33,
    product_name: "Carrot 500g",
    rateing: "4.1",
    quantity: "500g",
    current_price: 25,
    mrp: 80,
    discount: 68,
  },
  {
    mainid: "A2",
    id: 14,
    product: img34,
    product_name: "Bottle Gourd 1 unit",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 53,
    mrp: 65,
    discount: 18,
  },
  {
    mainid: "A2",
    id: 15,
    product: img35,
    product_name: "Coccinia 500g",
    rateing: "3.9",
    quantity: "500g",
    current_price: 43,
    mrp: 50,
    discount: 14,
  },
  {
    mainid: "A2",
    id: 16,
    product: img36,
    product_name: "Onion 500g",
    rateing: "4.3",
    quantity: "500g",
    current_price: 81,
    mrp: 130,
    discount: 24,
  },
  {
    mainid: "A2",
    id: 17,
    product: img37,
    product_name: "Mushroom Button 200g ",
    rateing: "4.2",
    quantity: "200g",
    current_price: 49,
    mrp: 60,
    discount: 18,
  },
  {
    mainid: "A2",
    id: 18,
    product: img38,
    product_name: "Cumcumber Local 1kg",
    rateing: "4",
    quantity: "1kg",
    current_price: 35,
    mrp: 70,
    discount: 50,
  },
  {
    mainid: "A2",
    id: 19,
    product: img39,
    product_name: "Sweet Corn Peeled 250g",
    rateing: "4",
    quantity: "250g",
    current_price: 35,
    mrp: 81,
    discount: 56,
  },
  {
    mainid: "A2",
    id: 20,
    product: img40,
    product_name: "Onion - Sambhar 500g",
    rateing: "3.9",
    quantity: "500g",
    current_price: 98,
    mrp: 130,
    discount: 24,
  },
  {
    mainid: "A2",
    id: 21,
    product: img41,
    product_name: "Beans Haricot 250g",
    rateing: "4.1",
    quantity: "250g",
    current_price: 50,
    mrp: 65,
    discount: 10,
  },
  {
    mainid: "A2",
    id: 22,
    product: img42,
    product_name: "Potato Agra 2kg",
    rateing: "4.3",
    quantity: "2kg",
    current_price: 131,
    mrp: 145,
    discount: 10,
  },
  {
    mainid: "A2",
    id: 23,
    product: img43,
    product_name: "banana Flower 1unit",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 32,
    mrp: 33,
    discount: 3,
  },
  {
    mainid: "A2",
    id: 24,
    product: img44,
    product_name: "Tomato Local Red 1kg",
    rateing: "4.5",
    quantity: "1kg",
    current_price: 84,
    mrp: 96,
    discount: 14,
  },
  {
    mainid: "A2",
    id: 25,
    product: img45,
    product_name: "Brinjal Bharta 500g",
    rateing: "4.2",
    quantity: "500g",
    current_price: 23,
    mrp: 26,
    discount: 11,
  },
  {
    mainid: "A2",
    id: 26,
    product: img46,
    product_name: "Chilli Green 100g",
    rateing: "4.2",
    quantity: "100g",
    current_price: 29,
    mrp: 32,
    discount: 5,
  },
  {
    mainid: "A2",
    id: 27,
    product: img47,
    product_name: "Beans Cluster 250g",
    rateing: "4.1",
    quantity: "250g",
    current_price: 18,
    mrp: 22,
    discount: 5,
  },
  {
    mainid: "A2",
    id: 28,
    product: img48,
    product_name: "Broccoli 1kg",
    rateing: "3.8",
    quantity: "1kg",
    current_price: 200,
    mrp: 250,
    discount: 20,
  },
  {
    mainid: "A2",
    id: 29,
    product: img49,
    product_name: "Beetroot 1kg",
    rateing: "4",
    quantity: "1kg",
    current_price: 77,
    mrp: 81,
    discount: 4,
  },
  {
    mainid: "A2",
    id: 30,
    product: img50,
    product_name: "Beans French 500g",
    rateing: "4",
    quantity: "500g",
    current_price: 38,
    mrp: 49,
    discount: 22,
  },
  {
    mainid: "A2",
    id: 31,
    product: img51,
    product_name: "Chow Chow 500g",
    rateing: "4.1",
    quantity: "500g",
    current_price: 55,
    mrp: 45,
    discount: 5,
  },
  {
    mainid: "A2",
    id: 32,
    product: img52,
    product_name: "Onion 1kg",
    rateing: "4.3",
    quantity: "1kg",
    current_price: 17,
    mrp: 39,
    discount: 56,
  },
  {
    mainid: "A2",
    id: 33,
    product: img53,
    product_name: "Tomato Hybrid 1kg",
    rateing: "4.3",
    quantity: "1kg",
    current_price: 48,
    mrp: 120,
    discount: 60,
  },
  {
    mainid: "A2",
    id: 34,
    product: img54,
    product_name: "Garlic Regular 500g",
    rateing: "4.6",
    quantity: "500g",
    current_price: 133,
    mrp: 235,
    discount: 43,
  },
  {
    mainid: "A2",
    id: 35,
    product: img55,
    product_name: "Garlic Peeled 100g",
    rateing: "4",
    quantity: "100g",
    current_price: 58,
    mrp: 65,
    discount: 10,
  },
  {
    mainid: "A2",
    id: 36,
    product: img56,
    product_name: "Beans 250g",
    rateing: "3.9",
    quantity: "250g",
    current_price: 23,
    mrp: 27,
    discount: 14,
  },
  {
    mainid: "A2",
    id: 37,
    product: img57,
    product_name: "Tomato Local 500g",
    rateing: "4",
    quantity: "500g",
    current_price: 20,
    mrp: 68,
    discount: 70,
  },
  {
    mainid: "A2",
    id: 38,
    product: img58,
    product_name: "Khol Khol 500g",
    rateing: "4.5",
    quantity: "500g",
    current_price: 42,
    mrp: 50,
    discount: 16,
  },
  {
    mainid: "A2",
    id: 39,
    product: img59,
    product_name: "Cabbage 1unit",
    rateing: "4.1",
    quantity: "1unit",
    current_price: 79,
    mrp: 86,
    discount: 11,
  },
  {
    mainid: "A2",
    id: 40,
    product: img60,
    product_name: "Cucumber 500g",
    rateing: "4.3",
    quantity: "500g",
    current_price: 34,
    mrp: 39,
    discount: 5,
  }
]
export const Api3 = [
  {
    mainid: "A3",
    id: 1,
    product: img61,
    product_name: "Debankan's natural Df Organic Plum250 1 kg",
    rateing: "4",
    quantity: "1kg",
    current_price: 254,
    mrp: 349,
    discount: 27,
  },
  {
    mainid: "A3",
    id: 2,
    product: img62,
    product_name: "Tender coconut 1 unit",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 126,
    mrp: 130,
    discount: 3,
  },
  {
    mainid: "A3",
    id: 3,
    product: img63,
    product_name: "Kiwi Green 1 kg",
    rateing: "4.2",
    quantity: "1kg",
    current_price: 151,
    mrp: 184,
    discount: 17,
  },
  {
    mainid: "A3",
    id: 4,
    product: img64,
    product_name: "Pomegranate 1 unit",
    rateing: "4.1",
    quantity: "1unit",
    current_price: 72,
    mrp: 157,
    discount: 54,
  },
  {
    mainid: "A3",
    id: 5,
    product: img65,
    product_name: "Watermelon Kiran 1 unit",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 42,
    mrp: 57,
    discount: 26,
  },
  {
    mainid: "A3",
    id: 6,
    product: img66,
    product_name: "Papaya Semi Ripe 1 unit",
    rateing: "3.6",
    quantity: "1 units",
    current_price: 63,
    mrp: 89,
    discount: 29,
  },
  {
    mainid: "A3",
    id: 7,
    product: img67,
    product_name: "Muskmelon 1 unit",
    rateing: "3.6",
    quantity: "1unit",
    current_price: 31,
    mrp: 60,
    discount: 48,
  },
  {
    mainid: "A3",
    id: 8,
    product: img68,
    product_name: "Pineapple 1 unit",
    rateing: "3.8",
    quantity: "1unit",
    current_price: 57,
    mrp: 140,
    discount: 59,
  },
  {
    mainid: "A3",
    id: 9,
    product: img69,
    product_name: "Apple Red Delicious 4 unit",
    rateing: "4",
    quantity: "1 unit",
    current_price: 188,
    mrp: 248,
    discount: 24,
  },
  {
    mainid: "A3",
    id: 10,
    product: img70,
    product_name: "Dragon Fruit 1 units",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 61,
    mrp: 130,
    discount: 53,
  },
  {
    mainid: "A3",
    id: 11,
    product: img71,
    product_name: "Sweet Lime Mosambi 1 kg",
    rateing: "4",
    quantity: "1 unit",
    current_price: 70,
    mrp: 113,
    discount: 38,
  },
  {
    mainid: "A3",
    id: 12,
    product: img72,
    product_name: "Apple Royal Gala 4 units",
    rateing: "4.1",
    quantity: "4 unit",
    current_price: 106,
    mrp: 265,
    discount: 60,
  },
  {
    mainid: "A3",
    id: 13,
    product: img73,
    product_name: "Orang Imported 4 unit",
    rateing: "4.1",
    quantity: "4 unit",
    current_price: 142,
    mrp: 170,
    discount: 16,
  },
  {
    mainid: "A3",
    id: 14,
    product: img74,
    product_name: "Hass Avacado 1 unit",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 107,
    mrp: 112,
    discount: 13,
  },
  {
    mainid: "A3",
    id: 15,
    product: img75,
    product_name: "Banana Red 500g",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 48,
    mrp: 97,
    discount: 50,
  },
  {
    mainid: "A3",
    id: 16,
    product: img76,
    product_name: "Papaya Raw 1 Units",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 35,
    mrp: 91,
    discount: 61,
  },
  {
    mainid: "A3",
    id: 17,
    product: img77,
    product_name: "Grapes Red Globe 250g",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 114,
    mrp: 135,
    discount: 15,
  },
  {
    mainid: "A3",
    id: 18,
    product: img78,
    product_name: "Apple Royal Gala 2 unit",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 66,
    mrp: 215,
    discount: 69,
  },
  {
    mainid: "A3",
    id: 19,
    product: img79,
    product_name: "Apple Shimla 4 units",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 114,
    mrp: 173,
    discount: 34,
  },
  {
    mainid: "A3",
    id: 20,
    product: img80,
    product_name: "Chelian Kiwi Green 3 units",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 130,
    mrp: 144,
    discount: 9,
  },
  {
    mainid: "A3",
    id: 21,
    product: img81,
    product_name: "Pear Naspatti 1 kg",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 146,
    mrp: 262,
    discount: 44,
  },
  {
    mainid: "A3",
    id: 22,
    product: img82,
    product_name: "Plum Indian 250g",
    rateing: "4",
    quantity: "1 unit",
    current_price: 57,
    mrp: 70,
    discount: 18,
  },
  {
    mainid: "A3",
    id: 23,
    product: img83,
    product_name: "Hass Avocado 2 unit",
    rateing: "3.9",
    quantity: "2 unit",
    current_price: 160,
    mrp: 193,
    discount: 17,
  },
  {
    mainid: "A3",
    id: 24,
    product: img84,
    product_name: "Washington Apple 2 units",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 110,
    mrp: 144,
    discount: 23,
  },
  {
    mainid: "A3",
    id: 25,
    product: img85,
    product_name: "Pomegranate Peeled 200g",
    rateing: "4.1",
    quantity: "200g",
    current_price: 104,
    mrp: 130,
    discount: 20,
  },
  {
    mainid: "A3",
    id: 26,
    product: img86,
    product_name: "Apple Red Delicious 2 units",
    rateing: "4.1",
    quantity: "2 unit",
    current_price: 89,
    mrp: 150,
    discount: 50,
  },
  {
    mainid: "A3",
    id: 27,
    product: img87,
    product_name: "Rambutan 250g",
    rateing: "4.2",
    quantity: "250g",
    current_price: 170,
    mrp: 258,
    discount: 34,
  },
  {
    mainid: "A3",
    id: 28,
    product: img88,
    product_name: " Washington Apple 4 units",
    rateing: "4.2",
    quantity: "2 unit",
    current_price: 248,
    mrp: 265,
    discount: 6,
  },
  {
    mainid: "A3",
    id: 29,
    product: img89,
    product_name: "Sweet Lime Mosambi 6units",
    rateing: "4",
    quantity: "2 unit",
    current_price: 78,
    mrp: 130,
    discount: 40,
  },
  {
    mainid: "A3",
    id: 30,
    product: img90,
    product_name: "Litchi 500g",
    rateing: "4.1",
    quantity: "2 unit",
    current_price: 200,
    mrp: 252,
    discount: 20,
  },
  {
    mainid: "A3",
    id: 31,
    product: img91,
    product_name: "Sapota Chikoo 250g",
    rateing: "3.5",
    quantity: "2 unit",
    current_price: 39,
    mrp: 43,
    discount: 9,
  },
  {
    mainid: "A3",
    id: 32,
    product: img92,
    product_name: "Pear Nashpati 500g",
    rateing: "3.3",
    quantity: "200g",
    current_price: 99,
    mrp: 120,
    discount: 15,
  },
  {
    mainid: "A3",
    id: 33,
    product: img93,
    product_name: "Figs Fresh 250g",
    rateing: "4.2",
    quantity: "2 unit",
    current_price: 78,
    mrp: 130,
    discount: 40,
  },
  {
    mainid: "A3",
    id: 34,
    product: img94,
    product_name: "Banana- Nendran 500g",
    rateing: "4.1",
    quantity: "2 unit",
    current_price: 23,
    mrp: 81,
    discount: 71,
  },
  {
    mainid: "A3",
    id: 35,
    product: img95,
    product_name: "Orange Nagpur Small 1 kg",
    rateing: "3.9",
    quantity: "2 unit",
    current_price: 202,
    mrp: 250,
    discount: 16,
  },
  {
    mainid: "A3",
    id: 36,
    product: img96,
    product_name: "Chelian Kiwi Green 6 Units",
    rateing: "4.0",
    quantity: "2 unit",
    current_price: 204,
    mrp: 262,
    discount: 22,
  },
  {
    mainid: "A3",
    id: 37,
    product: img97,
    product_name: "Apple Shimla Baby 1 kg",
    rateing: "2.7",
    quantity: "500g",
    current_price: 147,
    mrp: 221,
    discount: 33,
  },
  {
    mainid: "A3",
    id: 38,
    product: img98,
    product_name: "Orange Nagpur 1 kg",
    rateing: "3.8",
    quantity: "2 unit",
    current_price: 90,
    mrp: 181,
    discount: 50,
  },
  {
    mainid: "A3",
    id: 39,
    product: img99,
    product_name: "Urban Harvest Peeled Pomegranate Peeled 200 g",
    rateing: "4.1",
    quantity: "2 unit",
    current_price: 49,
    mrp: 127,
    discount: 61,
  },
  {
    mainid: "A3",
    id: 40,
    product: img100,
    product_name: "Plum Indian 500 g",
    rateing: "4",
    quantity: "2 unit",
    current_price: 180,
    mrp: 202,
    discount: 10,
  },
]
export const Api4 = [
  {
    mainid: "A4",
    id: 1,
    product: img101,
    product_name: "Govind Milk and milk products Tetra Lassi NA, 15 x 200 ml",
    rateing: "4.5",
    quantity: "1 unit",
    current_price: 329,
    mrp: 375,
    discount: 12,
  },
  {
    mainid: "A4",
    id: 2,
    product: img102,
    product_name: "Govind Milk and milk products Funzz Milk Shake,15 x 180 ml",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 450,
    mrp: 600,
    discount: 25,
  },
  {
    mainid: "A4",
    id: 3,
    product: img103,
    product_name: "Govind Milk and milk products Funzz Milk Shake, Rose, 12 x 200 ml",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 360,
    mrp: 540,
    discount: 35,
  },
  {
    mainid: "A4",
    id: 4,
    product: img104,
    product_name: "Govind Milk and milk products Funzz ",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 450,
    mrp: 600,
    discount: 25,
  },
  {
    mainid: "A4",
    id: 5,
    product: img105,
    product_name: "Govind Milk and milk products Govind UHT Toned Milk 1Lt",
    rateing: "4",
    quantity: "1 unit",
    current_price: 80,
    mrp: 132,
    discount: 37,
  },
  {
    mainid: "A4",
    id: 6,
    product: img106,
    product_name: "Govind Milk and milk products Mattha Tetra Pack, 15 x 180 ml",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 300,
    mrp: 480,
    discount: 38,
  },
  {
    mainid: "A4",
    id: 7,
    product: img107,
    product_name: "Govind Milk and milk products Funzz butterscotch,12 x 200 ml",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 360,
    mrp: 460,
    discount: 50,
  },
  {
    mainid: "A4",
    id: 8,
    product: img108,
    product_name: "Govind Milk and milk products Govind Milk & Milk ProductPack",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 710,
    mrp: 720,
    discount: 1,
  },
  {
    mainid: "A4",
    id: 9,
    product: img109,
    product_name: "Govind Milk and milk products Funzz Milk Shake Vanilla, 15 x 180 ml",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 450,
    mrp: 600,
    discount: 25,
  },
  {
    mainid: "A4",
    id: 10,
    product: img110,
    product_name: "Govind Milk and milk products Govind Toned Milk 15 x 180 ml",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 255,
    mrp: 360,
    discount: 25,
  },
  {
    mainid: "A4",
    id: 11,
    product: img111,
    product_name: "Amul Shrikhand Flavored Curd Elaichi",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 43,
    mrp: 52,
    discount: 17,
  },
  {
    mainid: "A4",
    id: 12,
    product: img112,
    product_name: "Milky Mist Stirred Fruit Yogurt Blueberry",
    rateing: "4",
    quantity: "1 unit",
    current_price: 27,
    mrp: 30,
    discount: 10,
  },
  {
    mainid: "A4",
    id: 13,
    product: img113,
    product_name: "MOTHER DAIRY Fruit Yogurt Mango",
    rateing: "4.6",
    quantity: "1 unit",
    current_price: 35,
    mrp: 42,
    discount: 12,
  },
  {
    mainid: "A4",
    id: 14,
    product: img114,
    product_name: "Amul Shrikhand Flavored Curd Badam, Pista",
    rateing: "3.7",
    quantity: "1 unit",
    current_price: 45,
    mrp: 47,
    discount: 4,
  },
  {
    mainid: "A4",
    id: 15,
    product: img115,
    product_name: "EPIGAMIA Fruit Yogurt Strawberry",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 70,
    mrp: 80,
    discount: 12,
  },
  {
    mainid: "A4",
    id: 16,
    product: img116,
    product_name: " Nestle a+ Greek Flavored Yogurt Strawberry",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 37,
    mrp: 45,
    discount: 17,
  },
  {
    mainid: "A4",
    id: 17,
    product: img117,
    product_name: "Nestle a+ Slim Dahi Plain Curd",
    rateing: "4.6",
    quantity: "1 unit",
    current_price: 76,
    mrp: 78,
    discount: 2,
  },
  {
    mainid: "A4",
    id: 18,
    product: img118,
    product_name: "iD Creamy Thick Plain Curd",
    rateing: "4.6",
    quantity: "1 unit",
    current_price: 75,
    mrp: 80,
    discount: 6,
  },
  {
    mainid: "A4",
    id: 19,
    product: img119,
    product_name: "Milky Mist Farm Fresh Plain Curd",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 120,
    mrp: 126,
    discount: 3,
  },
  {
    mainid: "A4",
    id: 20,
    product: img120,
    product_name: "Milky Mist Natural Greek Yogurt Plain Yogurt",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 35,
    mrp: 45,
    discount: 10,
  },
  {
    mainid: "A4",
    id: 21,
    product: img121,
    product_name: "Mamie Yova Deliciously French Fruit Yogurt Blueberry",
    rateing: "3",
    quantity: "1 unit",
    current_price: 55,
    mrp: 68,
    discount: 25,
  },
  {
    mainid: "A4",
    id: 22,
    product: img122,
    product_name: "Go Fresho A2 pure Gir Cow Ghee | Curd Churned Bilona A2",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 1025,
    mrp: 2449,
    discount: 50,
  },
  {
    mainid: "A4",
    id: 23,
    product: img123,
    product_name: "Go Fresho A2 Gir Cow ghee | Gir Cow Ghee | Pure desi ghee...",
    rateing: "4.5",
    quantity: "1 unit",
    current_price: 1401,
    mrp: 2559,
    discount: 45,
  },
  {
    mainid: "A4",
    id: 24,
    product: img124,
    product_name: "sanjeevani Organics Barsana Magic cow NETTLE Milk Fat S...",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 769,
    mrp: 855,
    discount: 10,
  },
  {
    mainid: "A4",
    id: 25,
    product: img125,
    product_name: "Earthen Story Premium A2 Desi Gir Cow Ghee | Bilona met...",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 1445,
    mrp: 3449,
    discount: 58,
  },
  {
    mainid: "A4",
    id: 26,
    product: img126,
    product_name: "AASHIRVAAD Svasti Pure Cow Ghee - Desi Ghee with Rich A...",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 616,
    mrp: 725,
    discount: 15,
  },
  {
    mainid: "A4",
    id: 27,
    product: img127,
    product_name: "Gowardhan COW GHEE RT PACK 1L 1 L Refill",
    rateing: "4",
    quantity: "1 unit",
    current_price: 660,
    mrp: 914,
    discount: 27,
  },
  {
    mainid: "A4",
    id: 28,
    product: img128,
    product_name: "PATANJALI Cow's Ghee, Danedar, Rich Aroma, Natural & He...",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 650,
    mrp: 780,
    discount: 16,
  },
  {
    mainid: "A4",
    id: 29,
    product: img129,
    product_name: "NESTLE Everyday Shahi Ghee 1 L Tetrapack",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 560,
    mrp: 630,
    discount: 11,
  },
  {
    mainid: "A4",
    id: 30,
    product: img130,
    product_name: "MOTHER DAIRY Buffalo Ghee 1 L Tetrapack",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 606,
    mrp: 675,
    discount: 10,
  },
  {
    mainid: "A4",
    id: 31,
    product: img131,
    product_name: "Farmer Fresh Ghee Jar (200ML) Ghee 200 ml Plastic Bottl.",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 189,
    mrp: 190,
    discount: 1,
  },
  {
    mainid: "A4",
    id: 32,
    product: img132,
    product_name: "Gavyamart Indian A2 Cow Ghee 100% Pure Non GMO - Made o...",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 4800,
    mrp: 5999,
    discount: 19,
  },
  {
    mainid: "A4",
    id: 33,
    product: img133,
    product_name: "Ananda Ghee 900 ml Tetrapack",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 513,
    mrp: 650,
    discount: 21,
  },
  {
    mainid: "A4",
    id: 34,
    product: img134,
    product_name: "PATANJALI Pure Danedar Cow Ghee with Rich Aroma, Natura...",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 649,
    mrp: 665,
    discount: 2,
  },
  {
    mainid: "A4",
    id: 35,
    product: img135,
    product_name: "dairy sagar COW DESI GHEE tetra pack of 1 Ghee 1000 ml ...",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 379,
    mrp: 620,
    discount: 38,
  },
  {
    mainid: "A4",
    id: 36,
    product: img136,
    product_name: "Rawat's Farm A2 Vedic Bilona Cow Ghee Made by Curd Chur...",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 584,
    mrp: 799,
    discount: 26,
  },
  {
    mainid: "A4",
    id: 37,
    product: img137,
    product_name: "Akshayakalpa Plain Mozzarella cheese Block",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 263,
    mrp: 349,
    discount: 24,
  },
  {
    mainid: "A4",
    id: 38,
    product: img138,
    product_name: "Amul Processed cheese Slices",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 116,
    mrp: 145,
    discount: 20,
  },
  {
    mainid: "A4",
    id: 39,
    product: img139,
    product_name: "Go Plain Processed cheese Slices",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 145,
    mrp: 165,
    discount: 12,
  },
  {
    mainid: "A4",
    id: 40,
    product: img140,
    product_name: "Amul Processed cheese Cubes",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 67,
    mrp: 135,
    discount: 50,
  },
  {
    mainid: "A4",
    id: 41,
    product: img141,
    product_name: "MOTHER DAIRY Plain Processed cheese Slices",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 108,
    mrp: 130,
    discount: 16,
  },
  {
    mainid: "A4",
    id: 42,
    product: img142,
    product_name: "Amul Plain Processed cheese Block",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 106,
    mrp: 130,
    discount: 18,
  },
  {
    mainid: "A4",
    id: 43,
    product: img143,
    product_name: "Milky Mist Plain Processed cheese Cubes",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 68,
    mrp: 160,
    discount: 57,
  },
  {
    mainid: "A4",
    id: 45,
    product: img144,
    product_name: "Amul Plain Processed cheese Slices",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 85,
    mrp: 175,
    discount: 52,
  },
  {
    mainid: "A4",
    id: 46,
    product: img145,
    product_name: "Go  Plain Processed cheese Block",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 86,
    mrp: 140,
    discount: 38,
  },
  {
    mainid: "A4",
    id: 47,
    product: img146,
    product_name: "Milky Mist Plain Processed cheese Block",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 64,
    mrp: 145,
    discount: 55,
  },
  {
    mainid: "A4",
    id: 48,
    product: img147,
    product_name: " Amul Spicey Garlic Processed cheese Spread",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 84,
    mrp: 110,
    discount: 23,
  },
  {
    mainid: "A4",
    id: 49,
    product: img148,
    product_name: "Go Pizza Processed cheese",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 125,
    mrp: 285,
    discount: 56,
  },
  {
    mainid: "A4",
    id: 50,
    product: img149,
    product_name: " Amul Salty Mozzarella and Cheddar Cheese Diced",
    rateing: "4",
    quantity: "1 unit",
    current_price: 125,
    mrp: 130,
    discount: 2,
  },
  {
    mainid: "A4",
    id: 51,
    product: img150,
    product_name: "Go Schezwan Processed cheese Slices",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 140,
    mrp: 164,
    discount: 12,
  },
  {
    mainid: "A4",
    id: 52,
    product: img151,
    product_name: " Nandini Pepper Processed cheese Spread ",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 79,
    mrp: 95,
    discount: 16,
  },
  {
    mainid: "A4",
    id: 53,
    product: img152,
    product_name: " Dlecta Plain Processed cheese Slices",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 97,
    mrp: 120,
    discount: 19,
  }
]
export const Api5 = [
  {
    mainid: "A5",
    id: 1,
    product: img153,
    product_name: "Heart Home Floral Print Plastic Dustbin, Pack of 2, Bla...",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 457,
    mrp: 899,
    discount: 49,
  },
  {
    mainid: "A5",
    id: 2,
    product: img154,
    product_name: "DREAM eHOME Air Conditioner Cover",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 256,
    mrp: 999,
    discount: 74,
  },
  {
    mainid: "A5",
    id: 3,
    product: img155,
    product_name: "Heart Home Royal Blue Plastic Dustbin, Pack of 2, Blank...",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 457,
    mrp: 899,
    discount: 49,
  },
  {
    mainid: "A5",
    id: 4,
    product: img156,
    product_name: "The Honest Home Company Aluminium Foil Paper Roll 18 Me...",
    rateing: "4",
    quantity: "1 unit",
    current_price: 156,
    mrp: 278,
    discount: 43,
  },
  {
    mainid: "A5",
    id: 5,
    product: img157,
    product_name: "Flipkart Supermart Home Essentials Lemon Dishwash Bar",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 45,
    mrp: 68,
    discount: 13,
  },
  {
    mainid: "A5",
    id: 6,
    product: img158,
    product_name: "Home-Secure Bed Bug Killer Spray-Natural Bed Bug Repell...",
    rateing: "3.5",
    quantity: "1 unit",
    current_price: 221,
    mrp: 399,
    discount: 44,
  },
  {
    mainid: "A5",
    id: 7,
    product: img159,
    product_name: "DREAM eHOME Water Purifier Cover",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 199,
    mrp: 599,
    discount: 66,
  },
  {
    mainid: "A5",
    id: 8,
    product: img160,
    product_name: "Established Home Actionware Premium Stainless Steel Wri...",
    rateing: "3.7",
    quantity: "1 unit",
    current_price: 1319,
    mrp: 2999,
    discount: 58,
  },
  {
    mainid: "A5",
    id: 9,
    product: img161,
    product_name: "HomeFast Aluminum Foil Butyl Waterproof Rubber Tape Adh...",
    rateing: "3.6",
    quantity: "1 unit",
    current_price: 177,
    mrp: 999,
    discount: 84,
  },
  {
    mainid: "A5",
    id: 10,
    product: img162,
    product_name: "Decent Home 140 TC Polycotton Single Abstract Flat Beds...",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 195,
    mrp: 999,
    discount: 80,
  },
  {
    mainid: "A5",
    id: 11,
    product: img163,
    product_name: "Luxurivo Home Velvet Prayer Mat",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 69,
    mrp: 799,
    discount: 91,
  },
  {
    mainid: "A5",
    id: 12,
    product: img164,
    product_name: "Home Tree Light weight and portable 5 Star 2700 mm Ultr...",
    rateing: "3.5",
    quantity: "1 unit",
    current_price: 969,
    mrp: 1260,
    discount: 23,
  },
  {
    mainid: "A5",
    id: 13,
    product: img165,
    product_name: "POUR HOME Car Freshener Diffuser",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 250,
    mrp: 268,
    discount: 6,
  },
  {
    mainid: "A5",
    id: 14,
    product: img166,
    product_name: "HomeStore-YEP Fitted King Size Waterproof Mattress Cove...",
    rateing: "3.5",
    quantity: "1 unit",
    current_price: 199,
    mrp: 1499,
    discount: 86,
  },
  {
    mainid: "A5",
    id: 15,
    product: img167,
    product_name: "MAA HOME CONCEPT Microfiber Floor Mat",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 149,
    mrp: 749,
    discount: 80,
  },
  {
    mainid: "A5",
    id: 16,
    product: img168,
    product_name: "MAA HOME CONCEPT Microfiber Floor Mat",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 142,
    mrp: 899,
    discount: 84,
  },
  {
    mainid: "A5",
    id: 17,
    product: img169,
    product_name: "POUR HOME French Flora, Red Rose & French Fusion Spray",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 387,
    mrp: 507,
    discount: 25,
  },
  {
    mainid: "A5",
    id: 18,
    product: img170,
    product_name: "HOME13 Round Oval Shoes laces Athletic Shoe Laces for S...",
    rateing: "3.7",
    quantity: "1 unit",
    current_price: 142,
    mrp: 399,
    discount: 64,
  },
  {
    mainid: "A5",
    id: 19,
    product: img171,
    product_name: "HOME13 Round Oval Shoes Laces For Sports/Running/Atheli...",
    rateing: "3.5",
    quantity: "1 unit",
    current_price: 139,
    mrp: 399,
    discount: 65,
  },
  {
    mainid: "A5",
    id: 20,
    product: img172,
    product_name: "POUR HOME Car Freshener Diffuser",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 250,
    mrp: 268,
    discount: 6,
  },
  {
    mainid: "A5",
    id: 21,
    product: img173,
    product_name: "The Honest Home Company Toilet Roll, 2PLY, Toilet Tissu...",
    rateing: "4",
    quantity: "1 unit",
    current_price: 187,
    mrp: 195,
    discount: 4,
  },
  {
    mainid: "A5",
    id: 22,
    product: img174,
    product_name: "Blessing Home Musical Activity Walker",
    rateing: "3.5",
    quantity: "1 unit",
    current_price: 549,
    mrp: 1599,
    discount: 65,
  },
  {
    mainid: "A5",
    id: 23,
    product: img175,
    product_name: "Heart Home 55 L Brown Laundry Basket",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 999,
    mrp: 1999,
    discount: 50,
  },
  {
    mainid: "A5",
    id: 24,
    product: img176,
    product_name: "MAA HOME CONCEPT Microfiber Floor Mat",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 149,
    mrp: 749,
    discount: 80,
  },
  {
    mainid: "A5",
    id: 25,
    product: img177,
    product_name: "ProHome 6 Steps Anti Slip Shoes Aluminium Ladder",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 2999,
    mrp: 11999,
    discount: 75,
  },
  {
    mainid: "A5",
    id: 26,
    product: img178,
    product_name: "Her Home Straight Drinking Straw",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 199,
    mrp: 1499,
    discount: 86,
  },
  {
    mainid: "A5",
    id: 27,
    product: img179,
    product_name: "Decent Home 140 TC Polycotton Single Abstract Flat Beds...",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 199,
    mrp: 999,
    discount: 50,
  },
  {
    mainid: "A5",
    id: 28,
    product: img180,
    product_name: "Raymond Home 104 TC Cotton Double Floral Flat Bedsheet",
    rateing: "4",
    quantity: "1 unit",
    current_price: 608,
    mrp: 1216,
    discount: 50,
  },
  {
    mainid: "A5",
    id: 29,
    product: img181,
    product_name: "JAGA HOME DECOR G Shape Cotton Solid Pregnancy Pillow P...",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 1199,
    mrp: 3999,
    discount: 70,
  },
  {
    mainid: "A5",
    id: 30,
    product: img182,
    product_name: "Decent Home 240 TC Cotton Double Floral Fitted (Elastic...",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 319,
    mrp: 2299,
    discount: 80,
  },
  {
    mainid: "A5",
    id: 31,
    product: img183,
    product_name: "Home Pictures 120 TC Microfiber Double Cartoon Flat Bed...",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 229,
    mrp: 999,
    discount: 77,
  },
  {
    mainid: "A5",
    id: 32,
    product: img184,
    product_name: "HomeMate Steel Floor Cloth Dryer Stand H-001",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 1299,
    mrp: 5999,
    discount: 78,
  },
  {
    mainid: "A5",
    id: 33,
    product: img185,
    product_name: "Home wood Engineered Wood TV Entertainment Unit ",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 1324,
    mrp: 1999,
    discount: 33,
  },
  {
    mainid: "A5",
    id: 34,
    product: img186,
    product_name: "POUR HOME Nector Lime Life All-purpose Air Freshener Bl...",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 285,
    mrp: 350,
    discount: 13,
  },
  {
    mainid: "A5",
    id: 35,
    product: img187,
    product_name: " Decent Home 240 TC Cotton Single Printed Flat Bedsheet",
    rateing: "3.7",
    quantity: "1 unit",
    current_price: 339,
    mrp: 999,
    discount: 60,
  },
  {
    mainid: "A5",
    id: 36,
    product: img188,
    product_name: "Appraise Home Impex Diyas Desigen Urli Bowl Colour Gold...",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 139,
    mrp: 999,
    discount: 86,
  },
  {
    mainid: "A5",
    id: 37,
    product: img189,
    product_name: "POUR HOME MULTIPLE Spray",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 358,
    mrp: 679,
    discount: 47,
  },
  {
    mainid: "A5",
    id: 38,
    product: img190,
    product_name: "Khadi Home Decor Cotton Pillows Cover",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 371,
    mrp: 599,
    discount: 38,
  },
  {
    mainid: "A5",
    id: 39,
    product: img191,
    product_name: "Decent Home 240 TC Cotton Double Floral Fitted (Elastic...",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 319,
    mrp: 2249,
    discount: 85,
  },
  {
    mainid: "A5",
    id: 40,
    product: img192,
    product_name: "Decent Home 240 TC Cotton Double Floral Fitted (Elastic...",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 319,
    mrp: 2249,
    discount: 85,
  },
]
export const Api6 = [
  {
    mainid: "A6",
    id: 1,
    product: img193,
    product_name: "KARACHI BAKERY Jeera Cookies",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 220,
    mrp: 350,
    discount: 27,
  },
  {
    mainid: "A6",
    id: 2,
    product: img194,
    product_name: "KARACHI BAKERY Fruit Cookies ",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 89,
    mrp: 95,
    discount: 6,
  },
  {
    mainid: "A6",
    id: 3,
    product: img195,
    product_name: "KARACHI BAKERY Fruit Biscuit Bakery Biscuit",
    rateing: "3.7",
    quantity: "1 unit",
    current_price: 190,
    mrp: 230,
    discount: 12,
  },
  {
    mainid: "A6",
    id: 4,
    product: img196,
    product_name: "KARACHI BAKERY Cashew Biscotti",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 190,
    mrp: 230,
    discount: 17,
  },
  {
    mainid: "A6",
    id: 5,
    product: img197,
    product_name: "Bakery Adda 30 cm Cake Dowel and Pillar",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 349,
    mrp: 499,
    discount: 30,
  },
  {
    mainid: "A6",
    id: 6,
    product: img198,
    product_name: "KARACHI BAKERY Cashew Biscuits Premium Pack Bakery Bisc...",
    rateing: "3.7",
    quantity: "1 unit",
    current_price: 220,
    mrp: 230,
    discount: 18,
  },
  {
    mainid: "A6",
    id: 7,
    product: img199,
    product_name: "Petilicious Bakery Goat Liver Jerky Dog Food Tasty Pet ...",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 185,
    mrp: 249,
    discount: 25,
  },
  {
    mainid: "A6",
    id: 8,
    product: img200,
    product_name: "Petilicious Bakery Petilicious Dry Chicken Crunches Jer...",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 175,
    mrp: 245,
    discount: 28,
  },
  {
    mainid: "A6",
    id: 9,
    product: img201,
    product_name: "Petilicious Bakery Buff Liver Jerky Dog Food Tasty Pet ...",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 279,
    mrp: 345,
    discount: 19,
  },
  {
    mainid: "A6",
    id: 10,
    product: img202,
    product_name: " Bombay bakery Mango Cookies Cookies",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 145,
    mrp: 150,
    discount: 3,
  },
  {
    mainid: "A6",
    id: 11,
    product: img203,
    product_name: " Bombay bakery Coconut Lachha Cookies ",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 145,
    mrp: 150,
    discount: 3,
  },
  {
    mainid: "A6",
    id: 12,
    product: img204,
    product_name: "Bombay bakery Fruits Jam Cookies Jam",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 145,
    mrp: 150,
    discount: 3,
  },
  {
    mainid: "A6",
    id: 13,
    product: img205,
    product_name: " Bombay bakery Peanut cookies Cookies",
    rateing: "2",
    quantity: "1 unit",
    current_price: 145,
    mrp: 150,
    discount: 3,
  },
  {
    mainid: "A6",
    id: 14,
    product: img206,
    product_name: "Bombay bakery Bakery Cookies",
    rateing: "3.2",
    quantity: "1 unit",
    current_price: 145,
    mrp: 150,
    discount: 3,
  },
  {
    mainid: "A6",
    id: 15,
    product: img207,
    product_name: " KARACHI BAKERY Fruit & Nut Cookies",
    rateing: "3.7",
    quantity: "1 unit",
    current_price: 180,
    mrp: 220,
    discount: 18,
  },
  {
    mainid: "A6",
    id: 16,
    product: img208,
    product_name: "Petilicious Bakery Petilicious Dry Ocean Flake Anchovie...",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 175,
    mrp: 249,
    discount: 29,
  },
  {
    mainid: "A6",
    id: 17,
    product: img209,
    product_name: "Petilicious Bakery Buff Liver Jerky Dog Food Tasty Pet ...",
    rateing: "4.3",
    quantity: "1 unit",
    current_price: 175,
    mrp: 249,
    discount: 29,
  },
  {
    mainid: "A6",
    id: 18,
    product: img210,
    product_name: " Petilicious Bakery Goat Liver Jerky Dog Food Tasty Pet ...",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 345,
    mrp: 450,
    discount: 23,
  },
  {
    mainid: "A6",
    id: 19,
    product: img211,
    product_name: "TummyFriendly Foods Ragi Millet Cookies - Assorted. Hea...",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 299,
    mrp: 596,
    discount: 49,
  },
  {
    mainid: "A6",
    id: 20,
    product: img212,
    product_name: " BAKEMATE Bourbon Chocolate Flavored Cream Filled Biscui...",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 220,
    mrp: 280,
    discount: 21,
  },
  {
    mainid: "A6",
    id: 21,
    product: img213,
    product_name: " Petilicious Bakery Petilicious Chicken Liver Chips Dog ...",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 175,
    mrp: 255,
    discount: 31,
  },
  {
    mainid: "A6",
    id: 22,
    product: img214,
    product_name: " KARACHI BAKERY Besan Ladoo Box ",
    rateing: "3.9",
    quantity: "1 unit",
    current_price: 160,
    mrp: 220,
    discount: 15,
  },
  {
    mainid: "A6",
    id: 23,
    product: img215,
    product_name: " Petilicious Bakery Tuna Fish Jerky Dog Food Tasty Pet T...",
    rateing: "2.8",
    quantity: "1 unit",
    current_price: 175,
    mrp: 249,
    discount: 29,
  },
  {
    mainid: "A6",
    id: 24,
    product: img216,
    product_name: " equisential Dry Fruit Laddu | Sugar Free | Sweet Delica...",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 423,
    mrp: 545,
    discount: 22,
  },
  {
    mainid: "A6",
    id: 25,
    product: img217,
    product_name: " MidBreak Sugar Free Jowar (Sorghum) Millets & Dry Fruit...",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 213,
    mrp: 250,
    discount: 14,
  },
  {
    mainid: "A6",
    id: 26,
    product: img218,
    product_name: " KARACHI BAKERY Plain Soan Papdi Mithai Box",
    rateing: "4",
    quantity: "1 unit",
    current_price: 52,
    mrp: 80,
    discount: 35,
  },
  {
    mainid: "A6",
    id: 27,
    product: img219,
    product_name: " Early Foods Pack of 2 - Millet Rusk, Jowar flavored Mil...Early Foods Pack of 2 - Millet Rusk, Jowar flavored Mil...",
    rateing: "4.4",
    quantity: "1 unit",
    current_price: 370,
    mrp: 480,
    discount: 22,
  },
  {
    mainid: "A6",
    id: 28,
    product: img220,
    product_name: " PARLE Nutricrunch Classic Digestive Cookies",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 309,
    mrp: 499,
    discount: 38,
  },
  {
    mainid: "A6",
    id: 29,
    product: img221,
    product_name: "KARACHI BAKERY Pista Soan Papdi Mithai Box",
    rateing: "3.8",
    quantity: "1 unit",
    current_price: 53,
    mrp: 80,
    discount: 33,
  },
  {
    mainid: "A6",
    id: 30,
    product: img222,
    product_name: "MidBreak Sugar Free Coconut Biscuits | High In",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 224,
    mrp: 230,
    discount: 2,
  },
  {
    mainid: "A6",
    id: 31,
    product: img223,
    product_name: "BAKEMATE Crispy Crumbs Osmania Cookies Combo Pack (75g ...",
    rateing: "4.8",
    quantity: "1 unit",
    current_price: 157,
    mrp: 180,
    discount: 12,
  },
  {
    mainid: "A6",
    id: 32,
    product: img224,
    product_name: "BAKEMATE Crispy Crumbs Choco Chip Cookies | Biscuits Co...",
    rateing: "4.8",
    quantity: "1 unit",
    current_price: 157,
    mrp: 180,
    discount: 12,
  },
  {
    mainid: "A6",
    id: 33,
    product: img225,
    product_name: " Bakery Adda Aluminium Cake Mould 3",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 499,
    mrp: 799,
    discount: 37,
  },
  {
    mainid: "A6",
    id: 34,
    product: img226,
    product_name: " Only Earth Drink Unsweetened , Almond, Oats, Coconut, 3 x 1 L ",
    rateing: "4.8",
    quantity: "1 unit",
    current_price: 885,
    mrp: 925,
    discount: 12,
  },
  {
    mainid: "A6",
    id: 35,
    product: img227,
    product_name: "Nature Vit Soy Milk Substitutes Powder",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 315,
    mrp: 400,
    discount: 21,
  },
  {
    mainid: "A6",
    id: 36,
    product: img228,
    product_name: " Farmer Fresh Every Time Dairy Creamer Best Dry for Tea ...",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 235,
    mrp: 249,
    discount: 5,
  },
  {
    mainid: "A6",
    id: 37,
    product: img229,
    product_name: "MOMADE MIRACLES Honey Oats Cookies | Healthy Cookies",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 249,
    mrp: 299,
    discount: 16,
  },
  {
    mainid: "A6",
    id: 38,
    product: img230,
    product_name: "JOLOCHIP Hottest CHIP Madness Last Challenge",
    rateing: "4.2",
    quantity: "1 unit",
    current_price: 248,
    mrp: 249,
    discount: 1,
  },
  {
    mainid: "A6",
    id: 39,
    product: img231,
    product_name: "Bakery Adda 1 Pc Stainless Steel, Plastic Knife 8 inch ...",
    rateing: "4",
    quantity: "1 unit",
    current_price: 175,
    mrp: 399,
    discount: 56,
  },
  {
    mainid: "A6",
    id: 40,
    product: img232,
    product_name: "Patna bakery Single Piece Square Slicer Black, Metal",
    rateing: "4.1",
    quantity: "1 unit",
    current_price: 70,
    mrp: 90,
    discount: 22,
  },
]
export const Api7 = [
  {
    mainid: "A7",
    id: 1,
    product: img233,
    product_name: "Sugar Free, Almond, Oats, Coconut, 2 x 1 L",
    rateing: "4.6",
    quantity: "1 unit",
    current_price: 885,
    mrp: 925,
    discount: 12,
  }
]